server:
  port: 8080
spring:
  application:
    name: hello-world
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
hello-world:
  greeting: "Olá"
  default-value: "Mundo"
